package com.example.agentweb.domain.workbench;

/**
 * Workbench 领域拒绝原因；Interface 可据此映射稳定错误合同。
 *
 * @author alex
 * @since 2026-08-01
 */
public enum WorkbenchErrorCode {
    REQUEST_INVALID,
    OWNER_REQUIRED,
    ARCHIVED,
    PHASE_RUN_ACTIVE,
    WRITE_RUN_ACTIVE,
    PHASE_RESTART_INVALID,
    PHASE_TRANSITION_INVALID,
    RUN_MODE_FORBIDDEN,
    CONVERSATION_CONFLICT,
    REPOSITORY_SCOPE_INVALID,
    IDEMPOTENCY_CONFLICT,
    RUN_BINDING_CORRUPTED,
    HANDOFF_SECRET_DETECTED,
    VERSION_CONFLICT,
    ATTACHMENT_INVALID,
    ATTACHMENT_TOO_LARGE,
    ATTACHMENT_LIMIT_EXCEEDED,
    ATTACHMENT_UNAVAILABLE,
    OPERATION_TRANSITION_INVALID,
    OPERATION_TARGET_CHANGED,
    OPERATION_EXECUTION_UNAVAILABLE
}
