package com.example.agentweb.domain.workbench;

/**
 * Workbench 领域拒绝原因；Interface 可据此映射稳定错误合同。
 *
 * @author alex
 * @since 2026-08-01
 */
public enum WorkbenchErrorCode {
    REQUEST_INVALID,
    OWNER_REQUIRED,
    ARCHIVED,
    WRITE_RUN_ACTIVE,
    STAGE_NOT_FOUND,
    STAGE_RUN_ACTIVE,
    STAGE_RESTART_INVALID,
    STAGE_TRANSITION_INVALID,
    RUN_MODE_FORBIDDEN,
    CONVERSATION_CONFLICT,
    REPOSITORY_SCOPE_INVALID,
    IDEMPOTENCY_CONFLICT,
    RUN_BINDING_CORRUPTED,
    VERSION_CONFLICT,
    ATTACHMENT_INVALID,
    ATTACHMENT_TOO_LARGE,
    ATTACHMENT_LIMIT_EXCEEDED,
    ATTACHMENT_UNAVAILABLE
}
