package com.example.agentweb.app.workbench;

/**
 * Workspace 基础设施失败的稳定应用错误码。
 *
 * @author alex
 * @since 2026-08-01
 */
public enum WorkspaceFailureCode {
    WORKSPACE_SELECTION_INVALID,
    WORKSPACE_PATH_FORBIDDEN,
    WORKSPACE_TOPOLOGY_CHANGED,
    WORKSPACE_CAPTURE_UNSTABLE,
    WORKSPACE_SELECTION_REQUIRED,
    WORKSPACE_REPOSITORY_NOT_FOUND,
    WORKSPACE_REPOSITORY_HEAD_MISSING,
    WORKSPACE_REPOSITORY_OVERLAP,
    WORKSPACE_GIT_UNAVAILABLE,
    WORKSPACE_DISCOVERY_LIMIT_EXCEEDED,
    WORKSPACE_MANIFEST_INVALID,
    REPOSITORY_SCOPE_VIOLATION
}
