<template>
  <admin-shell active="tool-invocation-analytics" @ready="onReady">
    <template #header-actions><el-button text :loading="loading" @click="loadAll">刷新</el-button></template>
    <div class="analytics" data-test="tool-invocation-analytics">
      <el-card shadow="never" class="filters" data-test="tool-statistics-filter">
        <el-form inline>
          <el-form-item label="时间"><el-select v-model="range" style="width:130px" @change="applyRange"><el-option label="最近7天" value="7"/><el-option label="最近30天" value="30"/><el-option label="最近90天" value="90"/><el-option label="全部" value="all"/></el-select></el-form-item>
          <el-form-item label="Provider"><el-select v-model="filter.provider" data-test="provider-filter" clearable style="width:120px"><el-option label="Claude" value="CLAUDE"/><el-option label="Codex" value="CODEX"/><el-option label="Native" value="NATIVE"/></el-select></el-form-item>
          <el-form-item label="类别"><el-select v-model="filter.invocationKind" clearable style="width:130px"><el-option label="工具" value="TOOL_USE"/><el-option label="命令执行" value="COMMAND_EXECUTION"/><el-option label="Skill" value="SKILL"/></el-select></el-form-item>
          <el-form-item label="状态"><el-select v-model="filter.status" clearable style="width:120px"><el-option v-for="s in statuses" :key="s" :label="statusLabel(s)" :value="s"/></el-select></el-form-item>
          <el-form-item label="来源"><el-select v-model="filter.source" data-test="source-filter" clearable style="width:150px"><el-option label="实时记录" value="LIVE"/><el-option label="历史迁移" value="HISTORY_MIGRATION"/></el-select></el-form-item>
          <el-button type="primary" @click="apply">应用</el-button><el-button @click="reset">重置</el-button>
        </el-form>
      </el-card>
      <el-alert v-if="overview" :closable="false" type="info" show-icon class="quality" :title="qualityText"/>
      <div v-if="overview" class="metric-grid" data-test="tool-statistics-overview">
        <el-card v-for="m in metrics" :key="m.label" shadow="never"><div class="metric-label">{{m.label}}</div><div class="metric-value">{{m.value}}</div><div class="metric-note">{{m.note}}</div></el-card>
      </div>
      <div class="two-columns">
        <el-card shadow="never"><template #header>每日调用量</template><div class="bars" data-test="tool-daily-trend"><div v-for="p in trend" :key="p.date" class="bar-col" :title="`${p.date}：${p.invocationCount} 次`"><div class="bar" :style="{height:barHeight(p.invocationCount)}"></div><small>{{p.date.slice(5)}}</small></div></div></el-card>
        <el-card shadow="never"><template #header>每日异常调用</template><el-table :data="trend.filter(p=>p.failedCount||p.incompleteCount).slice(-12)" size="small" max-height="260"><el-table-column prop="date" label="日期"/><el-table-column prop="failedCount" label="失败" align="right"/><el-table-column prop="incompleteCount" label="不完整" align="right"/></el-table></el-card>
      </div>
      <el-card shadow="never" class="section" data-test="tool-ranking-table"><template #header><b>调用排行</b></template>
        <el-tabs v-model="rankingType" @tab-change="loadRankings"><el-tab-pane label="工具" name="TOOL"/><el-tab-pane label="命令类别" name="COMMAND"/><el-tab-pane label="Skill" name="SKILL"/></el-tabs>
        <el-table :data="rankings" border size="small" empty-text="暂无排行数据"><el-table-column prop="analysisName" label="名称" min-width="180"/><el-table-column prop="invocationCount" label="调用" align="right"/><el-table-column prop="conversationCount" label="对话" align="right"/><el-table-column prop="succeededCount" label="成功" align="right"/><el-table-column prop="failedCount" label="失败" align="right"/><el-table-column label="失败率" align="right"><template #default="{row}">{{pct(row.failureRate)}}（{{row.failedCount}}/{{row.terminalCount}}）</template></el-table-column><el-table-column prop="outputTruncatedCount" label="输出截断" align="right"/><el-table-column label="操作"><template #default="{row}"><el-button text type="primary" @click="drillRanking(row.analysisName)">查看明细</el-button></template></el-table-column></el-table>
      </el-card>
      <el-card shadow="never" class="section" data-test="tool-conversation-ranking"><template #header><b>高调用对话</b></template>
        <el-table :data="conversations" border size="small" empty-text="暂无数据"><el-table-column prop="title" label="标题" min-width="220"><template #default="{row}">{{row.title||'新对话'}}</template></el-table-column><el-table-column prop="userName" label="用户"><template #default="{row}">{{row.userName||row.userId||'匿名/系统'}}</template></el-table-column><el-table-column prop="agentType" label="Agent"/><el-table-column prop="invocationCount" label="调用" align="right"/><el-table-column prop="failedCount" label="失败" align="right"/><el-table-column label="失败率" align="right"><template #default="{row}">{{pct(row.failureRate)}}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button text type="primary" @click="openConversation(row.sessionId)">查看对话</el-button></template></el-table-column></el-table>
      </el-card>
      <el-card shadow="never" class="section" data-test="tool-failure-table"><template #header><b>最近失败调用</b></template>
        <el-table :data="failures" border size="small"><el-table-column label="时间" width="170"><template #default="{row}">{{fmtTime(row.startedAt)}}</template></el-table-column><el-table-column prop="provider" label="Provider"/><el-table-column prop="displayToolName" label="工具 / Skill" min-width="180"/><el-table-column prop="outputSummary" label="输出摘要" min-width="260" show-overflow-tooltip/><el-table-column label="操作"><template #default="{row}"><el-button text type="primary" @click="openDetail(row.id)">详情</el-button></template></el-table-column></el-table>
      </el-card>
      <tool-invocation-detail-drawer v-model:open="detailOpen" :detail="detail" :display-name="detail?.displayToolName"/>
    </div>
  </admin-shell>
</template>
<script setup lang="ts">
import {computed,ref} from 'vue'; import {ElMessage} from 'element-plus'; import {fetchJson} from '../../lib/admin-fetch.ts'; import {formatStatisticsPercentage,statisticsDateRange,statisticsQualityText} from '../tool-invocation-statistics.ts'; import ToolInvocationDetailDrawer from '../components/ToolInvocationDetailDrawer.vue';
const loading=ref(false),overview=ref<any>(null),trend=ref<any[]>([]),rankings=ref<any[]>([]),conversations=ref<any[]>([]),failures=ref<any[]>([]),rankingType=ref('TOOL'),range=ref('30'),detailOpen=ref(false),detail=ref<any>(null);
const statuses=['STARTED','SUCCEEDED','FAILED','INCOMPLETE','UNKNOWN']; const filter=ref<any>({});
function applyRange(){if(range.value==='all'){delete filter.value.startedAfter;delete filter.value.startedBefore;return;}Object.assign(filter.value,statisticsDateRange(Number(range.value)))}
function params(extra:any={}){const p=new URLSearchParams();Object.entries({...filter.value,...extra}).forEach(([k,v])=>{if(v!==''&&v!=null)p.set(k,String(v))});return p}
async function loadAll(){loading.value=true;try{applyRange();const q=params().toString();const [o,t,c,f]=await Promise.all([fetchJson('/api/admin-tool-invocation-statistics/overview?'+q),fetchJson('/api/admin-tool-invocation-statistics/daily-trend?'+q),fetchJson('/api/admin-tool-invocation-statistics/conversations?'+params({size:20}).toString()),fetchJson('/api/admin-tool-invocations?'+params({status:'FAILED',size:20}).toString())]);overview.value=o;trend.value=t;conversations.value=c.items||[];failures.value=f.items||[];await loadRankings();history.replaceState(null,'','?'+q)}catch(e){ElMessage.error('加载工具分析失败：'+e)}finally{loading.value=false}}
async function loadRankings(){const d=await fetchJson('/api/admin-tool-invocation-statistics/rankings?'+params({type:rankingType.value,size:20}).toString());rankings.value=d.items||[]}
function apply(){loadAll()} function reset(){filter.value={};range.value='30';loadAll()} function drillRanking(analysisName:string){filter.value.analysisName=analysisName;loadAll()} function pct(v:any){return formatStatisticsPercentage(v)} function n(v:any){return Number(v||0).toLocaleString('zh-CN')}
const metrics=computed(()=>overview.value?[{label:'调用总数',value:n(overview.value.invocationCount),note:'当前筛选范围'},{label:'工具对话数',value:n(overview.value.conversationCount),note:'至少调用一次工具'},{label:'每工具对话平均调用',value:overview.value.averageInvocationsPerConversation?.toFixed(1)||'—',note:'调用数 ÷ 工具对话'},{label:'成功率',value:pct(overview.value.successRate),note:`成功 ${n(overview.value.succeededCount)}`},{label:'失败率',value:pct(overview.value.failureRate),note:`失败 ${n(overview.value.failedCount)}`},{label:'不完整调用',value:n(overview.value.incompleteCount),note:pct(overview.value.incompleteRate)}]:[])
const qualityText=computed(()=>statisticsQualityText(overview.value?.historyMigrationCount,overview.value?.liveCount))
async function onReady(){const query=new URLSearchParams(location.search);for(const key of ['startedAfter','startedBefore','provider','invocationKind','status','source','triggerSource','analysisName','sessionId','runId']){const value=query.get(key);if(value!=null)filter.value[key]=key==='startedAfter'||key==='startedBefore'?Number(value):value}if(filter.value.startedAfter||filter.value.startedBefore)range.value='all';await loadAll()}
function barHeight(v:number){const max=Math.max(1,...trend.value.map(x=>x.invocationCount));return Math.max(3,v/max*170)+'px'} function statusLabel(v:string){return({STARTED:'执行中',SUCCEEDED:'成功',FAILED:'失败',INCOMPLETE:'不完整',UNKNOWN:'未知'} as any)[v]||v} function fmtTime(v:number){return v?new Date(v).toLocaleString('zh-CN'):'—'} function openConversation(id:string){location.href='/admin/conversations.html?sessionId='+encodeURIComponent(id)} async function openDetail(id:number){detailOpen.value=true;detail.value=await fetchJson('/api/admin-tool-invocations/'+id)}
</script>
<style scoped>.analytics{display:grid;gap:16px}.filters :deep(.el-form-item){margin-bottom:0}.quality{margin-top:0}.metric-grid{display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));gap:12px}.metric-label,.metric-note{color:#909399;font-size:12px}.metric-value{font-size:25px;font-weight:700;margin:8px 0}.two-columns{display:grid;grid-template-columns:2fr 1fr;gap:16px}.bars{height:210px;display:flex;align-items:flex-end;gap:4px;overflow-x:auto}.bar-col{min-width:22px;text-align:center;color:#909399}.bar{background:#409eff;border-radius:4px 4px 0 0}.bar-col small{font-size:9px;writing-mode:vertical-rl;margin-top:4px}.section pre,pre{white-space:pre-wrap;word-break:break-all;max-height:420px;overflow:auto;background:#f5f7fa;padding:12px}@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(3,1fr)}.two-columns{grid-template-columns:1fr}}</style>
